services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8181:8181"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-port=8181
      - --import-realm
    volumes:
      - ./config/keycloak-realm.json:/opt/keycloak/data/import/realm.json